[project]
name = "fastapi-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "olivier ozdzinski", email = "olivier.godfrey@outlook.com" }
]
requires-python = ">=3.10"
dependencies = [
    "aiosqlite>=0.22.1",
    "fastapi>=0.141.1",
    "fastapi-users[sqlalchemy]>=15.0.5",
    "imagekitio>=5.9.0",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
    "streamlit>=1.63.0",
    "uvicorn[standard]>=0.52.4",
]

